package computerdatabase
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulation extends Simulation {

	val httpProtocol = http
		.baseUrl("https://computer-database.gatling.io")
		.inferHtmlResources(BlackList(""".*\.js""", """.*\.css""", """.*\.gif""", """.*\.jpeg""", """.*\.jpg""", """.*\.ico""", """.*\.woff""", """.*\.woff2""", """.*\.(t|o)tf""", """.*\.png""", """.*detectportal\.firefox\.com.*"""), WhiteList())
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.upgradeInsecureRequestsHeader("1")
		.userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0")

  /* Part of the autogenerated script
	val headers_5 = Map("Origin" -> "https://computer-database.gatling.io")
  */


	val scn = scenario("RecordedSimulation")
		.exec(http("request_0")
			.get("/computers"))
		.pause(809)
		.exec(http("request_1")
			.get("/computers"))
		.pause(163)
		.exec(http("request_2")
			.get("/computers?f=Apple"))
		.pause(15)
		.exec(http("request_3")
			.get("/computers?f=Dell"))
		.pause(2)
		.exec(http("request_4")
			.get("/computers/572"))
		.pause(24)
		.exec(http("request_5")
			.post("/computers/572")
			.headers(headers_5)
			.formParam("name", "Dell Vostro")
			.formParam("introduced", "")
			.formParam("discontinued", "")
			.formParam("company", "10"))
		.pause(81)
		.exec(http("request_6")
			.get("/computers?f=iPad"))
		.pause(7)
		.exec(http("request_7")
			.get("/computers/new"))
		.pause(22)
		.exec(http("request_8")
			.post("/computers")
			.headers(headers_5)
			.formParam("name", "iPad3")
			.formParam("introduced", "")
			.formParam("discontinued", "")
			.formParam("company", "1"))
		.pause(141)
		// ADD COMPUTER
		.exec(http("request_9")
			.get("/computers/new"))
		.pause(40)
		.exec(http("request_10")
			.post("/computers")
			.headers(headers_5)
			.formParam("name", "ASUS10")
			.formParam("introduced", "2021-04-07")
			.formParam("discontinued", "")
			.formParam("company", "36"))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
